services:
  redis:
    image: redis:latest
    container_name: blink-chat-backend-redis
    ports:
      - "6379:6379"
    volumes:
      - D:\docker-volume\blinkchat\redis:/data
    networks:
      - redis-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: blink-chat-backend-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - D:\docker-volume\blinkchat\redisinsight:/data
    environment:
      - REDIS_HOST=blink-chat-backend-redis
      - REDIS_PORT=6379
    depends_on:
      - blink-chat-backend-redis
    networks:
      - redis-network
      
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - D:\docker-volume\blinkchat\qdrant:/qdrant/storage:z
    networks:
      - redis-network
    
  backend:
    image: karansspl2021/blinkchatbackend:latest
    container_name: blinkchatbackend
    ports:
      - "5273:80"
    volumes:
      - D:\docker-volume\blinkchat\backend:/app/wwwroot
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - LM__licensekey=019B0C0-100235-C295A6-032129-B2D000-000525-049078-406173-9113D7-A2
      - ConnectionStrings__Redis=blink-chat-backend-redis:6379
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=5273
    networks:
      - redis-network

  frontend:
    image: karansspl2021/blinkchatfrontend:latest
    container_name: blinkchatfrontend
    ports:
      - "3000:3000"
    environment:
      - CHATBOT_API_BASE_URL=http://localhost:5273
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge